// Sample opportunities for demo mode (no Gemini key).
// Every project, client and figure below is fictional and for illustration only.
// Locations are real places so the map view has something meaningful to plot.
window.DEMO_OPPORTUNITIES = {
  hsr: [
    { regionGroup:'UK & Europe', title:'Northern Arc Metro Extension: Stations Design Package', client:'Regional Transit Authority (sample)', region:'Manchester, UK', lat:53.48, lng:-2.24, stage:'Procurement', urgency:'High', relevance:92, value:'£1.8bn', deadline:'Q1 2027', type:'Multidisciplinary Design', source:'Find a Tender (sample)',
      overview:'Design of six new underground stations on a 14 km metro extension, covering architecture, MEP and wayfinding. The appointment runs from concept through technical design.',
      context:'Part of a wider regional connectivity programme linking two growth corridors. Funding is committed for the first phase, with the second phase subject to a business case review in 2028.',
      gia:{ sectorFit:94, scaleFit:88, geoFit:90, winProb:62, verdict:'Strong fit. Station design at this scale matches recent references; partner with a local engineer for delivery credibility.' } },
    { regionGroup:'UK & Europe', title:'Iberian High Speed Link: Depot and Maintenance Facility', client:'National Rail Infrastructure Agency (sample)', region:'Valencia, Spain', lat:39.47, lng:-0.38, stage:'Pipeline', urgency:'Medium', relevance:78, value:'€640m', deadline:'Q3 2027', type:'Design & Build', source:'TED / OJEU (sample)',
      overview:'New rolling stock depot and maintenance facility serving a high speed corridor. Scope includes masterplanning of a 40 ha site and energy strategy.',
      context:'Prior information notice issued; formal tender expected within 12 months. The client is prioritising low-carbon construction and on-site renewables.',
      gia:{ sectorFit:76, scaleFit:70, geoFit:72, winProb:41, verdict:'Moderate fit. Depot work is adjacent to core strengths; worth tracking for the sustainability strategy lot.' } },
    { regionGroup:'Middle East', title:'Gulf Coast Light Rail: Line 2 Station Architecture', client:'Metropolitan Transport Commission (sample)', region:'Doha, Qatar', lat:25.29, lng:51.53, stage:'Live Tender', urgency:'High', relevance:88, value:'QAR 4.2bn', deadline:'Q4 2026', type:'Architectural Services', source:'Monaqasat (sample)',
      overview:'Architectural design of 11 elevated and at-grade stations with a shared kit-of-parts identity. Climate-responsive shading and passenger comfort are key evaluation criteria.',
      context:'Line 2 extends the existing network to new residential districts. The client has signalled a preference for firms with Gulf transit portfolios.',
      gia:{ sectorFit:90, scaleFit:84, geoFit:80, winProb:55, verdict:'Good fit. Climate-responsive station design is a differentiator; submission deadline is tight.' } },
    { regionGroup:'Asia Pacific', title:'Eastern Suburbs Metro: Interchange Precinct', client:'State Rail Delivery Office (sample)', region:'Sydney, Australia', lat:-33.87, lng:151.21, stage:'Procurement', urgency:'Medium', relevance:81, value:'A$2.1bn', deadline:'Q2 2027', type:'Design Consultancy', source:'AusTender (sample)',
      overview:'Design of a major interchange connecting a new metro line with bus and light rail. Includes over-station development envelopes.',
      context:'The state government has made integrated precincts a policy priority. Early contractor involvement is planned from stage 2.',
      gia:{ sectorFit:85, scaleFit:78, geoFit:66, winProb:44, verdict:'Good sector fit; geography is a stretch without a local office. Consider a joint venture.' } },
    { regionGroup:'Americas', title:'Pacific Corridor Regional Rail: Electrification Studies', client:'Regional Rail Joint Powers Board (sample)', region:'Portland, Oregon, USA', lat:45.52, lng:-122.68, stage:'Pipeline', urgency:'Low', relevance:64, value:'US$380m', deadline:'Q1 2028', type:'Feasibility & Planning', source:'SAM.gov (sample)',
      overview:'Feasibility and environmental studies for electrifying 160 km of regional rail. Includes station accessibility upgrades.',
      context:'Federal grant application is in preparation. Procurement will follow grant award, currently expected in 2027.',
      gia:{ sectorFit:60, scaleFit:58, geoFit:52, winProb:28, verdict:'Weak fit for now. Monitor the grant outcome before investing in pursuit.' } },
    { regionGroup:'Africa', title:'Coastal Commuter Rail Upgrade: Station Modernisation', client:'Metropolitan Rail Corporation (sample)', region:'Nairobi, Kenya', lat:-1.29, lng:36.82, stage:'Procurement', urgency:'Medium', relevance:73, value:'US$520m', deadline:'Q2 2027', type:'Design & Supervision', source:'African Development Bank (sample)',
      overview:'Modernisation of 18 commuter stations with new platforms, footbridges and passenger facilities. Development-bank funded with international competitive bidding.',
      context:'Part of a city mobility plan targeting modal shift from road. Social and environmental safeguards carry significant weight in evaluation.',
      gia:{ sectorFit:72, scaleFit:68, geoFit:60, winProb:38, verdict:'Moderate fit. Development-bank experience would strengthen the bid.' } },
  ],
  tod: [
    { regionGroup:'UK & Europe', title:'Riverside Station Quarter: TOD Masterplan', client:'City Development Corporation (sample)', region:'Leeds, UK', lat:53.80, lng:-1.55, stage:'Live Tender', urgency:'High', relevance:93, value:'£45m fees', deadline:'Q4 2026', type:'Masterplanning', source:'Contracts Finder (sample)',
      overview:'Masterplan for a 30 ha mixed-use quarter around an expanded mainline station. Up to 4,000 homes and 150,000 m² of workspace.',
      context:'Anchored by a committed station upgrade. The client wants a phased delivery strategy that attracts institutional investment.',
      gia:{ sectorFit:95, scaleFit:86, geoFit:92, winProb:64, verdict:'Excellent fit. Core TOD masterplanning in a home market; prioritise this pursuit.' } },
    { regionGroup:'UK & Europe', title:'Nordhafen Air Rights Development', client:'Municipal Real Estate Company (sample)', region:'Hamburg, Germany', lat:53.55, lng:9.99, stage:'Pipeline', urgency:'Medium', relevance:77, value:'€900m', deadline:'Q2 2027', type:'Design Competition', source:'TED / OJEU (sample)',
      overview:'Decking over active rail tracks to create a new urban block with housing and a public park. Two-stage international design competition.',
      context:'Competition brief expected early 2027. Structural and acoustic engineering over live rail is the key technical challenge.',
      gia:{ sectorFit:82, scaleFit:74, geoFit:70, winProb:35, verdict:'Good fit, but competitions are high-cost with uncertain returns. Bid only with a strong engineering partner.' } },
    { regionGroup:'Middle East', title:'Metro Line 4 Station Villages', client:'Urban Planning Council (sample)', region:'Riyadh, Saudi Arabia', lat:24.71, lng:46.68, stage:'Procurement', urgency:'High', relevance:87, value:'SAR 3.5bn', deadline:'Q1 2027', type:'Urban Design Framework', source:'Etimad (sample)',
      overview:'Urban design frameworks for walkable mixed-use villages around eight metro stations. Includes shaded public realm and last-mile mobility.',
      context:'Aligned with national quality-of-life targets. The client expects rapid mobilisation and a local presence.',
      gia:{ sectorFit:89, scaleFit:85, geoFit:78, winProb:52, verdict:'Strong fit. Emphasise climate-adapted public realm references.' } },
    { regionGroup:'Asia Pacific', title:'Harbourfront Interchange Precinct', client:'Land Development Authority (sample)', region:'Singapore', lat:1.26, lng:103.82, stage:'Awarded', urgency:'Low', relevance:70, value:'S$1.2bn', deadline:'Awarded Q2 2026', type:'Masterplanning', source:'GeBIZ (sample)',
      overview:'Integrated precinct masterplan above a new interchange station. Lead consultant appointed in 2026; specialist sub-consultant packages to follow.',
      context:'Main appointment is closed, but sustainability and lighting sub-packages are expected to be let during 2027.',
      gia:{ sectorFit:74, scaleFit:66, geoFit:64, winProb:30, verdict:'Main contract awarded. Approach the lead consultant about specialist sub-packages.' } },
    { regionGroup:'Americas', title:'Union Yards Transit Village', client:'Regional Transit District (sample)', region:'Denver, Colorado, USA', lat:39.74, lng:-104.99, stage:'Procurement', urgency:'Medium', relevance:79, value:'US$1.1bn', deadline:'Q1 2027', type:'Master Developer Partner', source:'State procurement portal (sample)',
      overview:'Selection of a master developer and design team for 20 ha of surplus rail land. Affordable housing target of 30%.',
      context:'Joint development model with the transit agency retaining land. Design lead will be named within developer consortia.',
      gia:{ sectorFit:80, scaleFit:76, geoFit:58, winProb:36, verdict:'Good fit if teamed with a developer bidder; do not bid standalone.' } },
    { regionGroup:'Africa', title:'Central Station Precinct Regeneration', client:'Metropolitan Municipality (sample)', region:'Johannesburg, South Africa', lat:-26.20, lng:28.05, stage:'Pipeline', urgency:'Low', relevance:66, value:'ZAR 6bn', deadline:'Q4 2027', type:'Feasibility & Masterplan', source:'eTenders South Africa (sample)',
      overview:'Precinct plan to reconnect a central station with surrounding districts. Includes informal trading, public realm and housing.',
      context:'Early-stage municipal initiative seeking co-funding. Timeline depends on a pending infrastructure fund decision.',
      gia:{ sectorFit:70, scaleFit:60, geoFit:55, winProb:25, verdict:'Early stage. Track and build client relationships before tender.' } },
  ],
  urb: [
    { regionGroup:'UK & Europe', title:'Eastern Docks Waterfront Regeneration', client:'Harbour Regeneration Partnership (sample)', region:'Bristol, UK', lat:51.45, lng:-2.59, stage:'Procurement', urgency:'High', relevance:91, value:'£1.2bn', deadline:'Q1 2027', type:'Masterplanning', source:'Find a Tender (sample)',
      overview:'Masterplan for a 45 ha former industrial waterfront with 3,500 homes, a cultural anchor and flood defences. Outline planning application within 18 months.',
      context:'Public-private partnership with land already assembled. Climate resilience and heritage retention are critical success factors.',
      gia:{ sectorFit:93, scaleFit:84, geoFit:91, winProb:60, verdict:'Excellent fit. Lead with waterfront and heritage-led regeneration references.' } },
    { regionGroup:'UK & Europe', title:'Porta Nord District Transformation', client:'City Urban Planning Department (sample)', region:'Milan, Italy', lat:45.46, lng:9.19, stage:'Live Tender', urgency:'Medium', relevance:80, value:'€750m', deadline:'Q4 2026', type:'Urban Design', source:'TED / OJEU (sample)',
      overview:'Urban design strategy for a former rail yard, creating a new district with a 10 ha park. Lots cover public realm, mobility and energy.',
      context:'Linked to the city\'s 2030 climate plan. Italian-language submission required, with a local partner expected.',
      gia:{ sectorFit:84, scaleFit:75, geoFit:68, winProb:40, verdict:'Good fit; language and local-partner requirements add bid cost.' } },
    { regionGroup:'Middle East', title:'Old Souk Heritage District Revitalisation', client:'Heritage and Tourism Authority (sample)', region:'Muscat, Oman', lat:23.59, lng:58.41, stage:'Procurement', urgency:'Medium', relevance:84, value:'OMR 180m', deadline:'Q1 2027', type:'Masterplan & Design Guidelines', source:'Tender Board Oman (sample)',
      overview:'Revitalisation masterplan for a historic trading district, balancing conservation with new hospitality and retail. Includes design codes.',
      context:'Tourism-led national strategy. Sensitive heritage context requires specialist conservation input.',
      gia:{ sectorFit:86, scaleFit:72, geoFit:76, winProb:47, verdict:'Good fit. Heritage credentials will be decisive.' } },
    { regionGroup:'Asia Pacific', title:'Canal District Urban Renewal', client:'Metropolitan Redevelopment Bureau (sample)', region:'Osaka, Japan', lat:34.69, lng:135.50, stage:'Pipeline', urgency:'Low', relevance:68, value:'¥180bn', deadline:'Q3 2027', type:'Concept Masterplan', source:'Japanese Government Procurement (sample)',
      overview:'Concept masterplan to renew an ageing canal-side district with mixed-use development and flood-resilient public space.',
      context:'Pre-procurement consultations underway. International firms typically join through Japanese lead consultants.',
      gia:{ sectorFit:72, scaleFit:66, geoFit:50, winProb:22, verdict:'Limited access for international firms; pursue only through a local partner.' } },
    { regionGroup:'Americas', title:'Southside Brownfield Innovation District', client:'City Economic Development Corporation (sample)', region:'Chicago, Illinois, USA', lat:41.88, lng:-87.63, stage:'Procurement', urgency:'High', relevance:83, value:'US$2.4bn', deadline:'Q4 2026', type:'Masterplanning', source:'City procurement portal (sample)',
      overview:'Masterplan for a 60 ha brownfield site as an innovation district with lab space, housing and a riverfront park.',
      context:'Anchor tenant agreements in negotiation. The city emphasises community benefits and local hiring.',
      gia:{ sectorFit:85, scaleFit:82, geoFit:60, winProb:42, verdict:'Strong sector and scale fit; team with a local firm for community engagement.' } },
    { regionGroup:'Africa', title:'New Waterfront City Centre Extension', client:'Urban Development Authority (sample)', region:'Accra, Ghana', lat:5.60, lng:-0.19, stage:'Procurement', urgency:'Medium', relevance:74, value:'US$950m', deadline:'Q2 2027', type:'Masterplan & Infrastructure', source:'World Bank (sample)',
      overview:'Masterplan and infrastructure design for a reclaimed-land city centre extension. Includes drainage, transport and social infrastructure.',
      context:'Development-bank backed with strict environmental safeguards. Integrated engineering capability is expected.',
      gia:{ sectorFit:76, scaleFit:78, geoFit:58, winProb:34, verdict:'Moderate fit; strong infrastructure partner required.' } },
  ],
  dc: [
    { regionGroup:'UK & Europe', title:'Thames Valley Hyperscale Campus: Phase 2', client:'Digital Infrastructure Developer (sample)', region:'Slough, UK', lat:51.51, lng:-0.59, stage:'Procurement', urgency:'High', relevance:86, value:'£1.5bn', deadline:'Q1 2027', type:'Design & Engineering', source:'Private tender (sample)',
      overview:'Design of three 60 MW data halls with an on-site substation and heat-recovery network. Planning submission targeted for late 2027.',
      context:'Grid capacity secured for phase 2. Heat export to a local district network is a planning condition.',
      gia:{ sectorFit:82, scaleFit:88, geoFit:90, winProb:50, verdict:'Good fit. Heat-recovery and sustainability credentials are the differentiator.' } },
    { regionGroup:'UK & Europe', title:'Nordic Green Data Park', client:'Regional Energy Company (sample)', region:'Luleå, Sweden', lat:65.58, lng:22.15, stage:'Pipeline', urgency:'Medium', relevance:75, value:'€1.1bn', deadline:'Q3 2027', type:'Masterplan & Campus Design', source:'TED / OJEU (sample)',
      overview:'Masterplan for a renewable-powered data park with space for four operators and shared cooling infrastructure.',
      context:'Hydropower supply agreements in place. Municipal zoning expected to be finalised in mid-2027.',
      gia:{ sectorFit:78, scaleFit:80, geoFit:62, winProb:33, verdict:'Moderate fit; strong sustainability angle but remote market.' } },
    { regionGroup:'Middle East', title:'Digital Oasis AI Compute Campus', client:'National Digital Infrastructure Fund (sample)', region:'Abu Dhabi, UAE', lat:24.45, lng:54.38, stage:'Live Tender', urgency:'High', relevance:90, value:'US$3.2bn', deadline:'Q4 2026', type:'Lead Design Consultant', source:'Abu Dhabi Procurement Portal (sample)',
      overview:'Lead design for a 300 MW AI compute campus with liquid cooling and solar-plus-storage. Includes an operator office and research hub.',
      context:'A flagship national AI strategy project. Fast-track programme with first capacity due in 2028.',
      gia:{ sectorFit:88, scaleFit:92, geoFit:82, winProb:48, verdict:'Strong fit at a very large scale. Resource the bid team early.' } },
    { regionGroup:'Asia Pacific', title:'Western Sydney Data Campus', client:'Data Centre REIT (sample)', region:'Sydney, Australia', lat:-33.82, lng:150.87, stage:'Procurement', urgency:'Medium', relevance:77, value:'A$1.4bn', deadline:'Q1 2027', type:'Design & Build', source:'Private tender (sample)',
      overview:'Design of a 150 MW campus in three phases near a new airport precinct. Water-efficient cooling is mandated.',
      context:'Part of a wider aerotropolis employment zone. Design-and-build contractors are leading bids with design partners.',
      gia:{ sectorFit:78, scaleFit:80, geoFit:62, winProb:35, verdict:'Moderate fit; join a contractor-led bid.' } },
    { regionGroup:'Americas', title:'Quarry Ridge Data Centre Campus', client:'Hyperscale Operator (sample)', region:'Querétaro, Mexico', lat:20.59, lng:-100.39, stage:'Pipeline', urgency:'Low', relevance:69, value:'US$900m', deadline:'Q2 2027', type:'Campus Masterplan', source:'CompraNet (sample)',
      overview:'Masterplan for a four-building campus on a former quarry site, including community amenities and water recycling.',
      context:'Operator is evaluating sites; final investment decision expected in 2027.',
      gia:{ sectorFit:70, scaleFit:74, geoFit:50, winProb:26, verdict:'Early and uncertain; monitor only.' } },
    { regionGroup:'Africa', title:'Lagos Digital Gateway Data Park', client:'Free Zone Development Company (sample)', region:'Lagos, Nigeria', lat:6.52, lng:3.38, stage:'Procurement', urgency:'Medium', relevance:72, value:'US$600m', deadline:'Q2 2027', type:'Masterplan & Engineering', source:'Free zone tender portal (sample)',
      overview:'Masterplan and engineering for a multi-tenant data park with a dedicated gas-to-power plant and subsea cable landing links.',
      context:'Strong regional demand growth. Power reliability is the defining design challenge.',
      gia:{ sectorFit:72, scaleFit:70, geoFit:56, winProb:32, verdict:'Moderate fit; requires specialist power engineering partner.' } },
  ],
  port: [
    { regionGroup:'UK & Europe', title:'Estuary Freeport Container Terminal Expansion', client:'Freeport Company (sample)', region:'Felixstowe, UK', lat:51.96, lng:1.35, stage:'Procurement', urgency:'High', relevance:82, value:'£780m', deadline:'Q1 2027', type:'Design & Engineering', source:'Find a Tender (sample)',
      overview:'Expansion of container berths with automated stacking, shore power and a new logistics park masterplan.',
      context:'Freeport tax incentives drive the programme. Shore power and decarbonisation are key evaluation criteria.',
      gia:{ sectorFit:78, scaleFit:80, geoFit:88, winProb:44, verdict:'Good fit for the logistics park and sustainability lots.' } },
    { regionGroup:'UK & Europe', title:'Baltic Cruise Terminal and Waterfront', client:'Port Authority (sample)', region:'Tallinn, Estonia', lat:59.44, lng:24.75, stage:'Live Tender', urgency:'Medium', relevance:76, value:'€210m', deadline:'Q4 2026', type:'Architectural Services', source:'TED / OJEU (sample)',
      overview:'New cruise terminal building and waterfront promenade linking the port to the old town.',
      context:'Tourism growth driving investment. Design quality and civic presence are emphasised in the brief.',
      gia:{ sectorFit:80, scaleFit:62, geoFit:66, winProb:40, verdict:'Good architectural fit; modest scale.' } },
    { regionGroup:'Middle East', title:'Red Sea Logistics Port: Phase 1', client:'Maritime Development Authority (sample)', region:'Jeddah, Saudi Arabia', lat:21.49, lng:39.19, stage:'Procurement', urgency:'High', relevance:85, value:'SAR 7bn', deadline:'Q1 2027', type:'Programme Management & Design', source:'Etimad (sample)',
      overview:'Phase 1 of a new logistics port with a container terminal, industrial zone and marine works.',
      context:'Part of a national logistics strategy. Programme management and masterplanning are procured separately.',
      gia:{ sectorFit:84, scaleFit:90, geoFit:80, winProb:43, verdict:'Strong fit for the masterplanning lot.' } },
    { regionGroup:'Asia Pacific', title:'Northern Bay Container Terminal', client:'Ports Corporation (sample)', region:'Colombo, Sri Lanka', lat:6.95, lng:79.84, stage:'Pipeline', urgency:'Low', relevance:67, value:'US$700m', deadline:'Q3 2027', type:'Feasibility Study', source:'Asian Development Bank (sample)',
      overview:'Feasibility and environmental studies for a deep-water container terminal.',
      context:'Development-bank technical assistance stage. Construction procurement is several years away.',
      gia:{ sectorFit:66, scaleFit:72, geoFit:54, winProb:24, verdict:'Early stage; low priority.' } },
    { regionGroup:'Americas', title:'Gulf Coast Offshore Wind Port', client:'State Port Authority (sample)', region:'Corpus Christi, Texas, USA', lat:27.80, lng:-97.40, stage:'Procurement', urgency:'Medium', relevance:78, value:'US$450m', deadline:'Q1 2027', type:'Design & Engineering', source:'SAM.gov (sample)',
      overview:'Heavy-lift quays and laydown areas to support offshore wind turbine assembly.',
      context:'Federal port infrastructure grants secured. Specialist marine engineering leads the team.',
      gia:{ sectorFit:74, scaleFit:70, geoFit:56, winProb:31, verdict:'Moderate fit; niche technical scope.' } },
    { regionGroup:'Africa', title:'Atlantic Deep-Water Port and Industrial Zone', client:'National Ports Agency (sample)', region:'Dakar, Senegal', lat:14.72, lng:-17.47, stage:'Procurement', urgency:'Medium', relevance:75, value:'US$1.3bn', deadline:'Q2 2027', type:'Masterplan & Design', source:'African Development Bank (sample)',
      overview:'Masterplan for a deep-water port with an adjoining special economic zone and rail connection.',
      context:'Co-financed by multilateral lenders. Integrated port-city planning is a priority.',
      gia:{ sectorFit:78, scaleFit:84, geoFit:60, winProb:36, verdict:'Good fit for the port-city masterplan.' } },
  ],
  mega: [
    { regionGroup:'UK & Europe', title:'National Health Estates Programme: Design Framework', client:'Health Infrastructure Programme Office (sample)', region:'London, UK', lat:51.51, lng:-0.13, stage:'Live Tender', urgency:'High', relevance:89, value:'£2.5bn framework', deadline:'Q4 2026', type:'Framework Agreement', source:'Crown Commercial Service (sample)',
      overview:'Multi-supplier design framework for a national hospital building programme using standardised designs.',
      context:'Framework places will be let for eight years. Modern methods of construction are central to the brief.',
      gia:{ sectorFit:86, scaleFit:92, geoFit:94, winProb:58, verdict:'Strong fit. Framework access unlocks a long pipeline.' } },
    { regionGroup:'UK & Europe', title:'Olympic Legacy Park Masterplan', client:'Games Organising Authority (sample)', region:'Paris, France', lat:48.92, lng:2.36, stage:'Pipeline', urgency:'Low', relevance:71, value:'€1.6bn', deadline:'Q2 2027', type:'Masterplanning', source:'BOAMP (sample)',
      overview:'Long-term masterplan converting former games venues into a mixed-use district.',
      context:'Planning framework under consultation; procurement likely in 2027.',
      gia:{ sectorFit:76, scaleFit:78, geoFit:70, winProb:30, verdict:'Moderate fit; monitor for the formal tender.' } },
    { regionGroup:'Middle East', title:'New Capital Government District: Phase 3', client:'Capital City Development Company (sample)', region:'New Administrative Capital, Egypt', lat:30.02, lng:31.73, stage:'Procurement', urgency:'High', relevance:84, value:'US$4bn', deadline:'Q1 2027', type:'Masterplan & Architecture', source:'Government procurement portal (sample)',
      overview:'Masterplan and architecture for ministry buildings and civic spaces in phase 3 of a new capital city.',
      context:'Fast-paced national programme. Payment security and currency risk should be assessed.',
      gia:{ sectorFit:82, scaleFit:94, geoFit:74, winProb:40, verdict:'Strong fit at a very large scale; commercial risk needs review.' } },
    { regionGroup:'Asia Pacific', title:'Northern Growth Corridor Programme Partner', client:'Infrastructure Commission (sample)', region:'Auckland, New Zealand', lat:-36.85, lng:174.76, stage:'Procurement', urgency:'Medium', relevance:79, value:'NZ$3bn', deadline:'Q1 2027', type:'Programme Management', source:'GETS (sample)',
      overview:'Programme partner for a 20-year growth corridor covering transport, housing and utilities.',
      context:'Alliance-style contracting model. Strong emphasis on Māori partnership and community outcomes.',
      gia:{ sectorFit:74, scaleFit:86, geoFit:56, winProb:32, verdict:'Moderate fit; the programme management scope is outside core strengths.' } },
    { regionGroup:'Americas', title:'World Cup Host City Infrastructure Programme', client:'Host City Delivery Office (sample)', region:'Monterrey, Mexico', lat:25.69, lng:-100.32, stage:'Live Tender', urgency:'High', relevance:77, value:'US$1.2bn', deadline:'Q4 2026', type:'Design Services', source:'CompraNet (sample)',
      overview:'Design of fan zones, transit upgrades and public realm for a major sporting event and its legacy.',
      context:'Immovable deadline creates delivery pressure. Legacy use is scored in evaluation.',
      gia:{ sectorFit:76, scaleFit:74, geoFit:52, winProb:30, verdict:'Moderate fit; the fixed deadline makes this a risky pursuit.' } },
    { regionGroup:'Africa', title:'Lake City Special Economic Zone', client:'Special Economic Zones Authority (sample)', region:'Kigali, Rwanda', lat:-1.95, lng:30.06, stage:'Pipeline', urgency:'Low', relevance:70, value:'US$800m', deadline:'Q3 2027', type:'Masterplan', source:'African Development Bank (sample)',
      overview:'Masterplan for a special economic zone with manufacturing, logistics and worker housing.',
      context:'Investment promotion stage. Procurement depends on anchor investor commitments.',
      gia:{ sectorFit:72, scaleFit:70, geoFit:54, winProb:26, verdict:'Early stage; build relationships with the authority.' } },
  ],
  env: [
    { regionGroup:'UK & Europe', title:'University Campus Net-Zero Energy Masterplan', client:'Research University (sample)', region:'Cambridge, UK', lat:52.21, lng:0.12, stage:'Live Tender', urgency:'High', relevance:94, value:'£3.2m fees', deadline:'Q4 2026', type:'Sustainability Consultancy', source:'Find a Tender (sample)',
      overview:'Campus-wide energy masterplan and utility vision plan to reach net zero by 2040, covering 120 buildings. Includes a whole life carbon baseline.',
      context:'The estates strategy commits to phasing out gas. The appointment could lead to MEP design roles on retrofit projects.',
      gia:{ sectorFit:96, scaleFit:78, geoFit:94, winProb:66, verdict:'Excellent fit. Campus energy masterplanning is a core strength; prioritise.' } },
    { regionGroup:'UK & Europe', title:'Civic Museum Retrofit: MEP and Lighting Design', client:'National Museums Trust (sample)', region:'Edinburgh, UK', lat:55.95, lng:-3.19, stage:'Procurement', urgency:'Medium', relevance:88, value:'£85m', deadline:'Q1 2027', type:'MEP & Lighting Design', source:'Public Contracts Scotland (sample)',
      overview:'MEP engineering and architectural lighting for the retrofit of a listed museum building, with conservation-grade environmental control.',
      context:'Heritage constraints and collection care drive the design. A low-carbon heating strategy is required.',
      gia:{ sectorFit:90, scaleFit:70, geoFit:92, winProb:58, verdict:'Strong fit. Combine heritage MEP and lighting references.' } },
    { regionGroup:'Middle East', title:'Airport Terminal Sustainability Framework', client:'Airports Company (sample)', region:'Dubai, UAE', lat:25.25, lng:55.36, stage:'Procurement', urgency:'High', relevance:86, value:'AED 40m fees', deadline:'Q1 2027', type:'Sustainability Framework', source:'Dubai eSupply (sample)',
      overview:'Sustainability framework and carbon strategy for a new terminal, covering energy, water, wellbeing and circularity.',
      context:'Part of a wider airport expansion. The framework will guide all downstream design packages.',
      gia:{ sectorFit:90, scaleFit:76, geoFit:80, winProb:52, verdict:'Strong fit. The framework role gives influence over later packages.' } },
    { regionGroup:'Asia Pacific', title:'Hospital Campus Climate Resilience Study', client:'State Health Infrastructure Agency (sample)', region:'Brisbane, Australia', lat:-27.47, lng:153.03, stage:'Live Tender', urgency:'Medium', relevance:80, value:'A$2.5m fees', deadline:'Q4 2026', type:'Climate Resilience Study', source:'QTenders (sample)',
      overview:'Climate risk and resilience study for a major hospital campus, covering flood, heat and energy security.',
      context:'Following recent extreme weather events. Outputs will inform a capital investment plan.',
      gia:{ sectorFit:84, scaleFit:62, geoFit:62, winProb:42, verdict:'Good fit; small fee but strategic entry to health clients.' } },
    { regionGroup:'Americas', title:'Cultural District Whole Life Carbon Assessment', client:'Arts District Foundation (sample)', region:'Toronto, Canada', lat:43.65, lng:-79.38, stage:'Procurement', urgency:'Medium', relevance:82, value:'C$1.8m fees', deadline:'Q1 2027', type:'Carbon Assessment', source:'MERX (sample)',
      overview:'Whole life carbon assessments and a carbon impact strategy for three new cultural buildings.',
      context:'The foundation targets net-zero-carbon certification. Embodied carbon reduction is scored heavily.',
      gia:{ sectorFit:88, scaleFit:60, geoFit:58, winProb:44, verdict:'Good fit; strong sustainability credentials needed.' } },
    { regionGroup:'Africa', title:'Regional Water Resilience Masterplan', client:'Water and Sanitation Authority (sample)', region:'Cape Town, South Africa', lat:-33.92, lng:18.42, stage:'Pipeline', urgency:'Low', relevance:71, value:'ZAR 120m fees', deadline:'Q2 2027', type:'Masterplanning', source:'eTenders South Africa (sample)',
      overview:'Water resilience masterplan covering demand management, reuse and nature-based solutions at city-region scale.',
      context:'Drought planning is a political priority. Procurement expected after budget approval.',
      gia:{ sectorFit:74, scaleFit:66, geoFit:56, winProb:30, verdict:'Moderate fit; the planning focus suits the sustainability team.' } },
  ],
};
